source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!

target “MJSwiftDoctor” do
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'SVProgressHUD'
    pod 'FSPagerView'
    pod 'TZImagePickerController'
    pod 'SwifterSwift', '~> 4.6'
    pod 'IQKeyboardManager'
    pod 'MJRefresh'
    pod 'RTRootNavigationController'
    pod 'AFNetworking'
    pod 'SwiftyJSON', '~> 4.2'
    pod 'Toast'
    pod 'XLPagerTabStrip'
    pod 'Segmentio'
    pod 'SGPagingView'
    pod 'CryptoSwift'
    pod 'YYModel'
    pod 'SDWebImage', '~> 4.0'
    pod 'Masonry'
    pod 'QCloudCOSXML'
    pod 'TYCyclePagerView'
    pod 'WZLBadge'
    pod 'JMessage'
  
end
